/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package htw.berlin.wi.prog2;

import htw.berlin.wi.prog2.service.BurgerBuilder;
import htw.berlin.wi.prog2.service.InputParser;
import htw.berlin.wi.prog2.service.SimpleInputParser;
import htw.berlin.wi.prog2.ui.CommandLineUI;
import htw.berlin.wi.prog2.ui.UserInputWrapper;

public class BurgerBotApp {
    public static void main(String[] args) {
        InputParser parser = new SimpleInputParser();
        BurgerBuilder builder = new BurgerBuilder();
        UserInputWrapper wrapper = new UserInputWrapper(System.in, System.out);
        CommandLineUI clui = new CommandLineUI(wrapper, builder, parser);
        clui.launch();
    }
}
